<?php
/*
    Nombre: head.inc
    Autor: Julio Tuozzo.
    Función: Header de las páginas.
    Fecha de creación: 17/05/2025.
    Ultima modificación: 17/05/2025.
*/
?>

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="./css/general.css">
    <title>Mercado Dios Me Libre</title>
</head>

<body>
    <header>
        <h1>Mercado Dios Me Libre...</h1>
        <h2>...de las cosas que tengo en casa y no uso</h2>
    </header>